language: objective-c
osx_image: xcode9.4

before_install:
  - brew update && brew bundle
  - carthage update --cache-builds --platform iOS

script:
  - xcodebuild -project Cobalt.xcodeproj -scheme Cobalt -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' clean build test
  - carthage build --cache-builds --platform iOS
