language: objective-c
osx_image: xcode10

cache: 
  directories:
  - Carthage
  - vendor/bundle

before_install:
  - brew update && brew bundle
  - carthage bootstrap --cache-builds --platform iOS

script:
  - xcodebuild -project Cobalt.xcodeproj -scheme Cobalt -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' clean build test
