language: objective-c
osx_image: xcode9.4

script:
  - pod install
  - xcodebuild -workspace Cobalt.xcworkspace -scheme Cobalt -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' clean build test
