language: objective-c
osx_image: xcode10.2

addons:
  homebrew:
    brewfile: true

branches:
  only:
  - master
  - accio

cache:
  directories:
  - vendor/bundle
  - .accio

before_install:
  - accio install

script:
  - xcodebuild -project Cobalt.xcodeproj -scheme Cobalt -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' clean build test
