language: objective-c
osx_image: xcode11

branches:
  only:
  - master

script:
  - xcodebuild -project Cobalt.xcodeproj -scheme Cobalt -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' clean build test
