language: objective-c
osx_image: xcode10.2

addons:
  homebrew:
    brewfile: true

branches:
  only:
  - master

cache:
  directories:
  - vendor/bundle
  - .accio

before_install:
  - mv _.xcodeproj Cobalt.xcodeproj
  - accio install
  - mv Cobalt.xcodeproj _.xcodeproj

script:
  - xcodebuild -project _.xcodeproj -scheme Cobalt -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' clean build test
