language: objective-c
osx_image: xcode10.2

addons:
  homebrew:
    brewfile: true

branches:
  only:
  - master

cache:
  directories:
  - vendor/bundle
  - Carthage

before_install:
  - carthage bootstrap --platform iOS --cache-builds

script:
  - xcodebuild -project Cobalt.xcodeproj -scheme Cobalt -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' clean build test
